apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ── Produção ────────────────────────────────────────────────────────────────
namespace: oficina-prod

resources:
  - ../../base
  - pdb.yaml

patches:
  - path: namespace.yaml
    target:
      kind: Namespace
      name: oficina
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
  - path: external-secret-patch.yaml

configMapGenerator:
  - name: oficina-config
    behavior: merge
    literals:
      - APP_ENV=production
      - APP_DEBUG=false
      - NEW_RELIC_APP_NAME=oficina-api-prod

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: oficina-api
    newName: oficina-api
    newTag: prod
