# Aponta o ExternalSecret para os segredos do ambiente hml.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oficina-secret
spec:
  data:
    - secretKey: DB_HOST
      remoteRef: { key: oficina/hml/db, property: host }
    - secretKey: DB_PORT
      remoteRef: { key: oficina/hml/db, property: port }
    - secretKey: DB_DATABASE
      remoteRef: { key: oficina/hml/db, property: dbname }
    - secretKey: DB_USERNAME
      remoteRef: { key: oficina/hml/db, property: username }
    - secretKey: DB_PASSWORD
      remoteRef: { key: oficina/hml/db, property: password }
    - secretKey: JWT_SECRET
      remoteRef: { key: oficina/hml/auth, property: JWT_SECRET }
    - secretKey: JWT_EXPIRATION
      remoteRef: { key: oficina/hml/auth, property: JWT_EXPIRATION }
    - secretKey: ADMIN_USERNAME
      remoteRef: { key: oficina/hml/auth, property: ADMIN_USERNAME }
    - secretKey: ADMIN_PASSWORD
      remoteRef: { key: oficina/hml/auth, property: ADMIN_PASSWORD }
    - secretKey: WEBHOOK_TOKEN
      remoteRef: { key: oficina/hml/auth, property: WEBHOOK_TOKEN }
